INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_IEEE_802_15_4_CUSTOMBLOCKS IEEE_802_15_4_CustomBlocks)

FIND_PATH(
    IEEE_802_15_4_CUSTOMBLOCKS_INCLUDE_DIRS
    NAMES IEEE_802_15_4_CustomBlocks/api.h
    HINTS $ENV{IEEE_802_15_4_CUSTOMBLOCKS_DIR}/include
        ${PC_IEEE_802_15_4_CUSTOMBLOCKS_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    IEEE_802_15_4_CUSTOMBLOCKS_LIBRARIES
    NAMES gnuradio-IEEE_802_15_4_CustomBlocks
    HINTS $ENV{IEEE_802_15_4_CUSTOMBLOCKS_DIR}/lib
        ${PC_IEEE_802_15_4_CUSTOMBLOCKS_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(IEEE_802_15_4_CUSTOMBLOCKS DEFAULT_MSG IEEE_802_15_4_CUSTOMBLOCKS_LIBRARIES IEEE_802_15_4_CUSTOMBLOCKS_INCLUDE_DIRS)
MARK_AS_ADVANCED(IEEE_802_15_4_CUSTOMBLOCKS_LIBRARIES IEEE_802_15_4_CUSTOMBLOCKS_INCLUDE_DIRS)

